version: '3'

services:
  hugo:
    build: .
    ports:
      - "1313:1313"
    volumes:
      - .:/app
    environment:
      - HUGO_ENV=development
    command: hugo server --bind 0.0.0.0 --disableFastRender -D