name: Copilot Setup Steps

on:
  # Run when GitHub Copilot is triggered
  # This workflow will be used by GitHub Copilot
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
        
      - name: Install Hugo
        run: |
          HUGO_VERSION=0.147.5
          HUGO_BINARY=hugo_${HUGO_VERSION}_Linux-amd64.tar.gz
          
          wget -q https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_BINARY}
          tar xzf ${HUGO_BINARY}
          sudo mv hugo /usr/local/bin/
          rm ${HUGO_BINARY}
          
          # Verify installation
          hugo version

      - name: Set up environment
        run: |
          echo "Hugo and Docker have been successfully set up for Copilot"